name: Deploy Frontend
on:
  push:
    branches:
      - 'main'
jobs:
  deployment:
    runs-on: "ubuntu-latest"
    environment: production
    steps:
      -
        name: Checkout source code
        uses: actions/checkout@v2
      - 
        name: Setup Node 
        uses: actions/setup-node@v2
        working-directory: ./client
        with:
          node-version: '16'
          cache: 'npm'
      - 
        name: NPM install 
        working-directory: ./client
        run: npm install

      - 
        name: NPM run test 
        working-directory: ./client
        run: npm test
      
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/docker-react:latest

      # - 
      #   name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v20
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: react-app
      #     environment_name: Reactapp-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-988335325762
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip
